Bitcoin-com/badger-mobile

components/TransactionRow/TransactionRow.js, data/store.js, data/transactions/actions.js, data/transactions/selectors.js, ios/Podfile, ios/Podfile.lock, ios/badgerMobile.xcodeproj/project.pbxproj, screens/WalletDetailScreen.js
* Fix ios build from package updates
* FromAddress fix causing unknown from transactions to crash app
* Fetch only transactions since last confirmed
* Adding transaction to redux cache
* fixes #16
=> Bug - Chris token crashes

components/TransactionRow/TransactionRow.js, data/transactions/reducer.js, screens/WalletDetailScreen.js
* Bug where transactions can appear multiple times
* Minor transaction history UI improvements
=> Bug - Multiple transactions

screens/HomeScreen.js, screens/SendConfirmScreen.js, screens/SendSetupScreen.js
Support fort BIP21 parameters in URI, with this PR only the `amount` value get set, but others do not break the QR scanning.
fixes #26
=> BIP21 basic - QR code amount param support

navigation/AuthLoadingScreen.js, navigation/AuthStack.js, navigation/MainTabNavigator.js, screens/HomeScreen.js, screens/LogoutScreen.js, screens/ReceiveScreen.js, screens/RestoreWalletScreen.js, screens/SendSetupScreen.js, screens/SettingsScreen.js, screens/ViewSeedScreen.js, screens/WelcomeScreen.js
* Better input for mnemonic, easier to enter the correct address
* UX/UI improvements throughout recovery flow
* Client validate that 12 words exist
* Auto lowercase mnemonic
* Logout screen explaining Mnemonic is needed to get into account and non-recoverable
* Extra steps to logout so it's not done accidentally 
fixes #20
=> Improvement - Mnemonic Flows

navigation/MainTabNavigator.js, package.json, screens/LogoutScreen.js, screens/PrivacyNoticeScreen.js, screens/SettingsScreen.js, screens/TermsOfUseScreen.js, yarn.lock
* ToS screen for new wallets
* Privacy policy screen for new wallets
* View both from settings
* Show app version in setting
fixes #21
=> Feature - Terms of use and Privacy policy

screens/WalletDetailScreen.js
link to explorer.bitcoin at the end of transaction history
adresses #7
=> Improvement - transaction history explorer

license
Adding the MIT license
fixes #48
=> License - MIT

screens/PrivacyNoticeScreen.js, screens/TermsOfUseScreen.js, screens/WelcomeScreen.js
* Remove Terms of Use and Privacy policy from new wallet flow
* Can be accessed at any time from settings
fixes #45
=> Improvement - Straight to new wallet

data/prices/reducer.js, navigation/AuthLoadingScreen.js, navigation/MainTabNavigator.js, package.json, screens/ContactUsScreen.js, screens/SettingsScreen.js, screens/WelcomeScreen.js
* Contact Us page in settings
* Email and Telegram links
* Adding a bunch of Badger emojis
=> Feature - contact us page

data/selectors.js, data/utxos/reducer.js, data/utxos/selectors.js, package.json, screens/CreateWalletScreen.js, screens/HomeScreen.js, screens/ViewSeedScreen.js, screens/WelcomeScreen.js, themes/spaceBadger.js
* Message when no SLP tokens present
* Message while initial UTXO load happens when restoring a wallet
* No longer caching UTXO's through logout, simplifies some logic
* More emoji's 🔧 
fixes #53
=> Improvement - on boarding upgrades

atoms/Button/Button.js, atoms/H1/H1.js, atoms/H2/H2.js, atoms/Spacer/Spacer.js, atoms/T/T.js, atoms/T/index.js, components/CoinRow/CoinRow.js, components/TransactionRow/TransactionRow.js, navigation/AuthLoadingScreen.js, package.json, screens/ContactUsScreen.js, screens/CreateWalletScreen.js, screens/HomeScreen.js, screens/LogoutScreen.js, screens/MenuScreen.js, screens/PrivacyNoticeScreen.js, screens/ReceiveScreen.js, screens/RestoreWalletScreen.js, screens/SendConfirmScreen.js, screens/SendSetupScreen.js, screens/SendSuccessScreen.js, screens/TermsOfUseScreen.js, screens/ViewSeedScreen.js, screens/WalletDetailScreen.js, screens/WelcomeScreen.js
* Massive `Spacing` and `font` overhaul, should appear much nicer on all phones, and everything has more breathing room and consistency
* `Send Max` added to send flow
* Removing emoji's since not every phone keeps up with the unicode spec
fixes #68 
fixes #70
=> Spacing, Send Max, and no emojis, oh my.

components/TransactionRow/TransactionRow.js, data/transactions/actions.js, data/transactions/reducer.js, package.json, screens/HomeScreen.js, screens/ReceiveScreen.js, screens/SendSetupScreen.js, screens/TermsOfUseScreen.js, screens/WalletDetailScreen.js, themes/spaceBadger.js, utils/balance-utils.js
* Better detection of history around SLP addresses.  
* Should show if it's going to the 145 or 245 address more accurately
* Fixed some visual bugs in history
* Fixed history not always adding up to the displayed amount
=> SLP History improvements

README.md, android/gradle.properties, data/store.js, ios/Podfile.lock, package.json, yarn.lock
* Async storage, bit faster
* Library updates
=> Library updates - preparing more for launch

.gitignore, README.md, package.json, screens/SendConfirmScreen.js, screens/TermsOfUseScreen.js, utils/transaction-utils.js
* Surface sending errors to the user. 
* Bugfix sending transactions with too many UTXOs
fixes #77 
fixes #72
=> Feature - transaction error surfacing improvements

data/accounts/actions.js, data/accounts/reducer.js, data/selectors.js, data/utxos/reducer.js, package.json, screens/SendConfirmScreen.js, screens/SendSetupScreen.js, screens/WalletDetailScreen.js, utils/balance-utils.js
* No longer show negative balance on send when wallet empty, caused by removing the transaction fee.
* Use BigNumber in more places for consistency and speed
* Fixing some visual bugs caused by using numbers and BigNumbers together
* Adding / fixing some flow type annotations
fixes #87
=> Bug - initial value negative send screen

screens/HomeScreen.js, screens/TermsOfUseScreen.js, screens/WalletDetailScreen.js, utils/currency-utils.js
* Fixing crash when visiting a token which hasn't loaded data yet
* Adding more fiat conversions to cover most of the widely used currencies around the world.
* Patch in minor ToU updates from website
fixes #91 
fixes #29
=> Crashing no metadata && More fiat curencies

screens/SendConfirmScreen.js, screens/SendSetupScreen.js
* Fixes a bug which prevented sending SLP tokens which do not have a ticker, such as the SLP torch.
=> Bug - send tokens no ticker

CHANGELOG.md, README.md, ios/badgerMobile/Info.plist
* Final updates for 0.7.0 release
* Multiple Fiat currencies
* Multiple bug fixes
=> Release - 0.7.0

ios/badgerMobile/Info.plist, package.json, screens/SendSetupScreen.js
* Fixing edge case crash when sending all tokens, then sending again immediately
=> 0.7.1 - Minor crash fix

screens/SendConfirmScreen.js, screens/SendSuccessScreen.js
* Shows errors from SLP transactions, such as when there is no BCH to pay the tx fee.
=> Bug - Surface errors from SLP transactions

android/app/build.gradle, ios/badgerMobile/Info.plist, navigation/AuthLoadingScreen.js, package.json, screens/SendSetupScreen.js
=> Hotfix - Fixing launch crash on android

android/app/build.gradle, ios/badgerMobile/Info.plist, navigation/AuthLoadingScreen.js, package.json, screens/SendSetupScreen.js
* Fixing launch crash on android
=> Hotfix - Fixing launch crash on android (#127)

data/utxos/actions.js
* Make unknown SLP token UTXO's unspendable 
fixes #129
=> Bug - Make unknown SLP types unspendable

screens/SendSetupScreen.js
=> Bug - Crash sending to invalid address

SMOKE_TESTS.md
Basic document to outline major flows which should be checked before every production release.
=> Doc - Basic smoke test document

data/store.js, data/transactions/actions.js, utils/balance-utils.js
* Still get SLP history even when the BCH history has an error
* Small cleanup to history fetching code so BCH for 145 and 245 is fetched in a single request
=> Bug - history not appearing correct

navigation/MainTabNavigator.js, screens/FAQScreen.js, screens/MenuScreen.js
* New FAQ screen to cover commonly asked questions
* Very basic initially, can add as needed
fixes #60
=> Screen -  FAQ screen 

CHANGELOG.md, README.md, ios/badgerMobile.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, screens/FAQScreen.js, screens/KeySweepScreen.js, screens/MenuScreen.js
* FAQ tweaks
* intructions for sweep
* Changelog entry for 0.11.0
=> Tweaks for 0.11.0 releease

android/app/build.gradle, data/tokens/actions.js, ios/badgerMobile.xcodeproj/project.pbxproj, package.json, screens/FAQScreen.js, screens/MenuScreen.js, screens/ReceiveScreen.js, utils/balance-utils.js, utils/transaction-utils.js
* No longer show NFT tokens at all.
* Improved error if more than 25 inputs
* Some code DRYing
* Use BitDB and SLPDB through Bitbox instead of direct
* Improving receive screen.  See screenshot
fixes #170 
fixes #174 
fixes #178
=> NFT fix, new receive screen

CHANGELOG.md, SMOKE_TESTS.md, android/app/build.gradle, ios/badgerMobile.xcodeproj/project.pbxproj, package.json, screens/MenuScreen.js, screens/SendSetupScreen.js
Comparison is off so often the user is told they don't have enough tokens even when they do.
fixes #183
=> Hotfix - Tokens cannot send sometimes

android/app/build.gradle, ios/badgerMobile.xcodeproj/project.pbxproj, package.json, screens/KeySweepScreen.js, screens/MenuScreen.js
Ensure the token metadata exists before trying to display it.
If a tokens metadata doesn't exist, fetch it's details.
fixes #206
=> Bug - Sweeping unknown tokens

screens/Bip70ConfirmScreen.js, screens/WalletDetailScreen.js, utils/bip70-utils.js
Fixing issue where BIP70 with OP_RETURNS are not paying fee correct
fixes #201
=> Bug - BIP 70 with OP_RETURN fee calculation
